; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define ToolName "Handwriting Keyboard"
#define ToolVersion "1.0.0"
#define ToolPublisher "DeepMind Pair Programming"
#define ToolURL "https://github.com/google-deepmind"
#define ToolExeName "handwriting_keyboard.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
AppId={{5D0B14A9-0B78-43B0-9A2E-82C3D35E445F}
AppName={#ToolName}
AppVersion={#ToolVersion}
AppPublisher={#ToolPublisher}
AppPublisherURL={#ToolURL}
AppSupportURL={#ToolURL}
AppUpdatesURL={#ToolURL}
DefaultDirName={autopf}\{#ToolName}
DisableProgramGroupPage=yes
; We require administrative privileges so that system font registration (AddFontResource + HKLM font listing) works correctly.
PrivilegesRequired=admin
OutputDir=build\windows\installer
OutputBaseFilename=handwriting_keyboard_setup
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "build\windows\runner\Release\{#ToolExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "build\windows\runner\Release\*.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "build\windows\runner\Release\data\*"; DestDir: "{app}\data"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\{#ToolName}"; Filename: "{app}\{#ToolExeName}"
Name: "{autodesktop}\{#ToolName}"; Filename: "{app}\{#ToolExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#ToolExeName}"; Description: "{cm:LaunchProgram,{#StringChange(ToolName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
